# Generated by Django 5.2.3 on 2025-06-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomoneda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='criptomoneda',
            name='precio_actual',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='criptomoneda',
            name='ultima_actualizacion',
            field=models.DateTimeField(),
        ),
    ]
