# Generated by Django 5.2.3 on 2025-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0002_alter_criptomoneda_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criptomoneda',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
